### ISSUE TITLE
handle negative numbers and small floats

### ISSUE THREAD

**Issue by louperelo** [nfdi4plants/nf-core-pipeline-to-arc#9]
# PROBLEM
CWL converts all numbers smaller than 1e-5 to a string, even if the default is given as a number (0.00001)
```
- id: annotation_prokka_evalue
 type: float?
 default: 0.00001
 inputBinding:
 prefix: --annotation_prokka_evalue
```
gives this error:
```
ERROR: Validation of pipeline parameters failed!
* --annotation_prokka_evalue: expected type: Number, found: String (1e-05)
```
It does not happen for floats >0.0001, though. Also, negative numbers in the default are passed as a string.

# SOLUTION
Define these numbers as strings in the `.cwl` file, e.g.:
```
type: string?
default: '0.000001'
```
# TASK
The defaults taken from the `nextflow_schema.json` have either to be checked if they are <0.0001 and if so, written to the `.cwl` file as `string?` *OR* all input taken from the `.json` has to be written as a `string?` in the `.cwl`.
